#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BreakableWindow_Importer

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BreakableWindow_Importer.BP_BreakableWindow_Importer_C
// 0x0030 (0x02C8 - 0x0298)
class ABP_BreakableWindow_Importer_C final : public AActor
{
public:
	class UChildActorComponent*                   ChildActor;                                        // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Arch_Blockout_Dealer_Office_Window_Av_NoGlass;  // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class UMaterialInterface*>             Glass_Mesh_Materials;                              // 0x02B0(0x0010)(Edit, BlueprintVisible)
	class UFMODEvent*                             WindowBreakToPlay;                                 // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BreakableWindow_Importer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BreakableWindow_Importer_C")
	}
	static class ABP_BreakableWindow_Importer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_BreakableWindow_Importer_C>();
	}
};
DUMPER7_ASSERTS_ABP_BreakableWindow_Importer_C;

}

