#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Bus

#include "Basic.hpp"

#include "BP_SplineVehicles_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Bus.BP_Bus_C
// 0x0000 (0x0340 - 0x0340)
class ABP_Bus_C final : public ABP_SplineVehicles_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Bus_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Bus_C")
	}
	static class ABP_Bus_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Bus_C>();
	}
};
DUMPER7_ASSERTS_ABP_Bus_C;

}

