#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CoverLandmark_Corner

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CoverLandmark_Corner.BP_CoverLandmark_Corner_C
// 0x0000 (0x05E0 - 0x05E0)
class ABP_CoverLandmark_Corner_C final : public ACoverLandmark
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CoverLandmark_Corner_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CoverLandmark_Corner_C")
	}
	static class ABP_CoverLandmark_Corner_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CoverLandmark_Corner_C>();
	}
};
DUMPER7_ASSERTS_ABP_CoverLandmark_Corner_C;

}

