#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Destructible_DonationBox

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Destructible_DonationBox.BP_Destructible_DonationBox_C
// 0x0020 (0x02F0 - 0x02D0)
class ABP_Destructible_DonationBox_C final : public ADynamicWorldItem
{
public:
	class UStaticMeshComponent*                   SM_StackedCash_01_C2;                              // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_StackedCash_01_C1;                              // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_StackedCash_01_C;                               // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Random_Mesh;                                       // 0x02E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Destructible_DonationBox_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Destructible_DonationBox_C")
	}
	static class ABP_Destructible_DonationBox_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Destructible_DonationBox_C>();
	}
};
DUMPER7_ASSERTS_ABP_Destructible_DonationBox_C;

}

