#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Destructible_PoliceCar

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Destructible_Vehicle_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Destructible_PoliceCar.BP_Destructible_PoliceCar_C
// 0x0108 (0x0608 - 0x0500)
class ABP_Destructible_PoliceCar_C final : public ABP_Destructible_Vehicle_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Destructible_PoliceCar_C;        // 0x0500(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UPointLightComponent*                   BlueLight;                                         // 0x0508(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UPointLightComponent*                   RedLight;                                          // 0x0510(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           AntenaBack;                                        // 0x0518(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           Wiper_R;                                           // 0x0520(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           Wiper_L;                                           // 0x0528(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           Antena;                                            // 0x0530(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     RedGlass;                                          // 0x0538(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     BlueGlass;                                         // 0x0540(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           Siren_Base;                                        // 0x0548(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           Bulba;                                             // 0x0550(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           Hood;                                              // 0x0558(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           Boot;                                              // 0x0560(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  RearWindshieldParticle;                            // 0x0568(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     RearWindshield;                                    // 0x0570(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           RearViewMirror;                                    // 0x0578(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  FrontWindshieldParticle;                           // 0x0580(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     FrontWindshield;                                   // 0x0588(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  BackRightDoorParticle;                             // 0x0590(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     BackRightDoorGlass;                                // 0x0598(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           BackRightDoor;                                     // 0x05A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  BackLeftDoorParticle;                              // 0x05A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     BackLeftDoorGlass;                                 // 0x05B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           BackLeftDoor;                                      // 0x05B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  FrontRightDoorParticle;                            // 0x05C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           FrontRightDoorMirror;                              // 0x05C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     FrontRightDoorGlass;                               // 0x05D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           FrontRightDoor;                                    // 0x05D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  FrontLeftDoorParticle;                             // 0x05E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           FrontLeftDoorMirror;                               // 0x05E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     FrontLeftDoorGlass;                                // 0x05F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           FrontLeftDoor;                                     // 0x05F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          PoliceLightsON_;                                   // 0x0600(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void ExecuteUbergraph_BP_Destructible_PoliceCar(int32 EntryPoint);
	void BndEvt__BP_Destructible_PoliceCar_RedGlass_K2Node_ComponentBoundEvent_1_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit);
	void BndEvt__BP_Destructible_PoliceCar_BlueGlass_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Destructible_PoliceCar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Destructible_PoliceCar_C")
	}
	static class ABP_Destructible_PoliceCar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Destructible_PoliceCar_C>();
	}
};
DUMPER7_ASSERTS_ABP_Destructible_PoliceCar_C;

}

