#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Destructible_ClassicTruck

#include "Basic.hpp"

#include "BP_Destructible_Vehicle_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Destructible_ClassicTruck.BP_Destructible_ClassicTruck_C
// 0x0068 (0x0568 - 0x0500)
class ABP_Destructible_ClassicTruck_C final : public ABP_Destructible_Vehicle_Base_C
{
public:
	class UDestructibleVehicleBodyPart*           RearViewMirror;                                    // 0x0500(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  RearWindshieldParticle;                            // 0x0508(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     RearWindshield;                                    // 0x0510(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  FrontWindshieldParticle;                           // 0x0518(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     FrontWindshield;                                   // 0x0520(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  FrontRightDoorParticle;                            // 0x0528(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           FrontRightDoorMirror;                              // 0x0530(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     FrontRightDoorGlass;                               // 0x0538(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           FrontRightDoor;                                    // 0x0540(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  FrontLeftDoorParticle;                             // 0x0548(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           FrontLeftDoorMirror;                               // 0x0550(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     FrontLeftDoorGlass;                                // 0x0558(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           FrontLeftDoor;                                     // 0x0560(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Destructible_ClassicTruck_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Destructible_ClassicTruck_C")
	}
	static class ABP_Destructible_ClassicTruck_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Destructible_ClassicTruck_C>();
	}
};
DUMPER7_ASSERTS_ABP_Destructible_ClassicTruck_C;

}

