#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Destructible_Mug_Set_04

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Destructible_Mug_Set_04.BP_Destructible_Mug_Set_04_C
// 0x0008 (0x02D8 - 0x02D0)
class ABP_Destructible_Mug_Set_04_C final : public ADynamicWorldItem
{
public:
	class UStaticMeshComponent*                   Random_Mesh;                                       // 0x02D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Destructible_Mug_Set_04_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Destructible_Mug_Set_04_C")
	}
	static class ABP_Destructible_Mug_Set_04_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Destructible_Mug_Set_04_C>();
	}
};
DUMPER7_ASSERTS_ABP_Destructible_Mug_Set_04_C;

}

