#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Destructible_Orderscreen

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Destructible_Orderscreen.BP_Destructible_Orderscreen_C
// 0x0000 (0x02D0 - 0x02D0)
class ABP_Destructible_Orderscreen_C final : public ADynamicWorldItem
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Destructible_Orderscreen_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Destructible_Orderscreen_C")
	}
	static class ABP_Destructible_Orderscreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Destructible_Orderscreen_C>();
	}
};
DUMPER7_ASSERTS_ABP_Destructible_Orderscreen_C;

}

