#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Destruction_Chips_Var1

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Destruction_Chips_Var1.BP_Destruction_Chips_Var1_C
// 0x0000 (0x02D0 - 0x02D0)
class ABP_Destruction_Chips_Var1_C final : public ADynamicWorldItem
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Destruction_Chips_Var1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Destruction_Chips_Var1_C")
	}
	static class ABP_Destruction_Chips_Var1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Destruction_Chips_Var1_C>();
	}
};
DUMPER7_ASSERTS_ABP_Destruction_Chips_Var1_C;

}

