#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Destructible_DeliveryTruck_Postal

#include "Basic.hpp"

#include "BP_Destructible_Vehicle_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Destructible_DeliveryTruck_Postal.BP_Destructible_DeliveryTruck_Postal_C
// 0x0070 (0x0570 - 0x0500)
class ABP_Destructible_DeliveryTruck_Postal_C final : public ABP_Destructible_Vehicle_Base_C
{
public:
	class UDestructibleVehicleBodyPart*           RightSideMirror_02;                                // 0x0500(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           RightSideMirror_01;                                // 0x0508(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           LeftSideMirror_02;                                 // 0x0510(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleBodyPart*           LeftSideMirror_01;                                 // 0x0518(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  FrontRightDoorParticle;                            // 0x0520(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     FrontRightDoorGlass;                               // 0x0528(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     FrontLeftDoorGlass;                                // 0x0530(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  BackSideGlasParticle_R;                            // 0x0538(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     BackSideGlass_R;                                   // 0x0540(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  BackSideGlasParticle_L;                            // 0x0548(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     BackSideGlass_L;                                   // 0x0550(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  FrontWindshieldParticle;                           // 0x0558(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleGlassComponent*     FrontWindshield;                                   // 0x0560(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UDestructibleVehicleParticleComponent*  FrontLeftDoorParticle;                             // 0x0568(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Destructible_DeliveryTruck_Postal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Destructible_DeliveryTruck_Postal_C")
	}
	static class ABP_Destructible_DeliveryTruck_Postal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Destructible_DeliveryTruck_Postal_C>();
	}
};
DUMPER7_ASSERTS_ABP_Destructible_DeliveryTruck_Postal_C;

}

