#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Evidence_Glock

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Evidence_Glock.BP_Evidence_Glock_C
// 0x0000 (0x0360 - 0x0360)
class ABP_Evidence_Glock_C final : public AEvidenceActor
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Evidence_Glock_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Evidence_Glock_C")
	}
	static class ABP_Evidence_Glock_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Evidence_Glock_C>();
	}
};
DUMPER7_ASSERTS_ABP_Evidence_Glock_C;

}

