#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Objective_Importer_RescueEugeneGomez

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Objective_Importer_RescueEugeneGomez.BP_Objective_Importer_RescueEugeneGomez_C
// 0x0000 (0x0348 - 0x0348)
class ABP_Objective_Importer_RescueEugeneGomez_C final : public ARescueCivilianByTag
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Objective_Importer_RescueEugeneGomez_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Objective_Importer_RescueEugeneGomez_C")
	}
	static class ABP_Objective_Importer_RescueEugeneGomez_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Objective_Importer_RescueEugeneGomez_C>();
	}
};
DUMPER7_ASSERTS_ABP_Objective_Importer_RescueEugeneGomez_C;

}

