#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Objective_Importer_ArrestMariaLopez

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Objective_Importer_ArrestMariaLopez.BP_Objective_Importer_ArrestMariaLopez_C
// 0x0000 (0x0338 - 0x0338)
class ABP_Objective_Importer_ArrestMariaLopez_C final : public ANeutralizeSuspectByTag
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Objective_Importer_ArrestMariaLopez_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Objective_Importer_ArrestMariaLopez_C")
	}
	static class ABP_Objective_Importer_ArrestMariaLopez_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Objective_Importer_ArrestMariaLopez_C>();
	}
};
DUMPER7_ASSERTS_ABP_Objective_Importer_ArrestMariaLopez_C;

}

