#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Objective_Importer_Reportable_Downedsuspect

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Objective_Importer_Reportable_Downedsuspect.BP_Objective_Importer_Reportable_Downedsuspect_C
// 0x0000 (0x0330 - 0x0330)
class ABP_Objective_Importer_Reportable_Downedsuspect_C final : public AReportReportableByTag
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Objective_Importer_Reportable_Downedsuspect_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Objective_Importer_Reportable_Downedsuspect_C")
	}
	static class ABP_Objective_Importer_Reportable_Downedsuspect_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Objective_Importer_Reportable_Downedsuspect_C>();
	}
};
DUMPER7_ASSERTS_ABP_Objective_Importer_Reportable_Downedsuspect_C;

}

