#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ReportableActor_Importer_Office

#include "Basic.hpp"

#include "BP_ReportableActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ReportableActor_Importer_Office.BP_ReportableActor_Importer_Office_C
// 0x0000 (0x0380 - 0x0380)
class ABP_ReportableActor_Importer_Office_C final : public ABP_ReportableActor_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ReportableActor_Importer_Office_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ReportableActor_Importer_Office_C")
	}
	static class ABP_ReportableActor_Importer_Office_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ReportableActor_Importer_Office_C>();
	}
};
DUMPER7_ASSERTS_ABP_ReportableActor_Importer_Office_C;

}

