#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SM_Trailer_Module_V2A

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SM_Trailer_Module_V2A.BP_SM_Trailer_Module_V2A_C
// 0x0008 (0x02A0 - 0x0298)
class ABP_SM_Trailer_Module_V2A_C final : public AActor
{
public:
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SM_Trailer_Module_V2A_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SM_Trailer_Module_V2A_C")
	}
	static class ABP_SM_Trailer_Module_V2A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SM_Trailer_Module_V2A_C>();
	}
};
DUMPER7_ASSERTS_ABP_SM_Trailer_Module_V2A_C;

}

