#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SubLevelManager

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_SubLevelManager.BP_SubLevelManager_C
// 0x0020 (0x02B8 - 0x0298)
class ABP_SubLevelManager_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class FName>                           LevelList;                                         // 0x02A8(0x0010)(Edit, BlueprintVisible, Net)

public:
	void UpdateLevelStreaming();
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_SubLevelManager(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SubLevelManager_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SubLevelManager_C")
	}
	static class ABP_SubLevelManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SubLevelManager_C>();
	}
};
DUMPER7_ASSERTS_ABP_SubLevelManager_C;

}

