#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WeaponCache_LargeCrate

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_WeaponCache_LargeCrate.BP_WeaponCache_LargeCrate_C.ReportToTOC
// 0x0010 (0x0010 - 0x0000)
struct BP_WeaponCache_LargeCrate_C_ReportToTOC final
{
public:
	class AReadyOrNotCharacter*                   Reporter;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          bPlayAnimation;                                    // 0x0008(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_WeaponCache_LargeCrate_C_ReportToTOC;

// Function BP_WeaponCache_LargeCrate.BP_WeaponCache_LargeCrate_C.ExecuteUbergraph_BP_WeaponCache_LargeCrate
// 0x0018 (0x0018 - 0x0000)
struct BP_WeaponCache_LargeCrate_C_ExecuteUbergraph_BP_WeaponCache_LargeCrate final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AReadyOrNotCharacter*                   K2Node_Event_Reporter;                             // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bPlayAnimation;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_WeaponCache_LargeCrate_C_ExecuteUbergraph_BP_WeaponCache_LargeCrate;

}

