#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_WeaponCache_LargeCrate

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_WeaponCacheActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_WeaponCache_LargeCrate.BP_WeaponCache_LargeCrate_C
// 0x0030 (0x0368 - 0x0338)
class ABP_WeaponCache_LargeCrate_C final : public ABP_WeaponCacheActor_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_WeaponCache_LargeCrate_C;        // 0x0338(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UFMODAudioComponent*                    FMODAudio;                                         // 0x0340(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Plane;                                             // 0x0348(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 WeaponMesh2;                                       // 0x0350(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 WeaponMesh1;                                       // 0x0358(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x0360(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReportToTOC(class AReadyOrNotCharacter* Reporter, bool bPlayAnimation);
	void Multicast_OnEvidenceCollected();
	void ExecuteUbergraph_BP_WeaponCache_LargeCrate(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_WeaponCache_LargeCrate_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_WeaponCache_LargeCrate_C")
	}
	static class ABP_WeaponCache_LargeCrate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_WeaponCache_LargeCrate_C>();
	}
};
DUMPER7_ASSERTS_ABP_WeaponCache_LargeCrate_C;

}

