#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CyberneticsSuspect_V2

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CyberneticsSuspect_V2.CyberneticsSuspect_V2_C
// 0x0010 (0x2790 - 0x2780)
class ACyberneticsSuspect_V2_C final : public ASuspectCharacter
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x2780(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class FName                                   In_Bone_Name;                                      // 0x2788(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_CyberneticsSuspect_V2(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("CyberneticsSuspect_V2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"CyberneticsSuspect_V2_C")
	}
	static class ACyberneticsSuspect_V2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACyberneticsSuspect_V2_C>();
	}
};
DUMPER7_ASSERTS_ACyberneticsSuspect_V2_C;

}

