#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CyberneticsSuspect_V2

#include "Basic.hpp"


namespace SDK::Params
{

// Function CyberneticsSuspect_V2.CyberneticsSuspect_V2_C.ExecuteUbergraph_CyberneticsSuspect_V2
// 0x0004 (0x0004 - 0x0000)
struct CyberneticsSuspect_V2_C_ExecuteUbergraph_CyberneticsSuspect_V2 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_CyberneticsSuspect_V2_C_ExecuteUbergraph_CyberneticsSuspect_V2;

}

