#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HangingMainLamp

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HangingMainLamp.HangingMainLamp_C
// 0x0030 (0x02C8 - 0x0298)
class AHangingMainLamp_C final : public AActor
{
public:
	class USpotLightComponent*                    SpotLight1;                                        // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USpotLightComponent*                    SpotLight;                                         // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   ceilinglight_01;                                   // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_DataCentre_Cables_B_holder_large1;              // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_DataCentre_Cables_B_holder_large;               // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HangingMainLamp_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HangingMainLamp_C")
	}
	static class AHangingMainLamp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHangingMainLamp_C>();
	}
};
DUMPER7_ASSERTS_AHangingMainLamp_C;

}

