#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Hospital_CeilingLight_Warm_NoShadow

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Hospital_CeilingLight_Warm_NoShadow.Hospital_CeilingLight_Warm_NoShadow_C
// 0x0020 (0x02B8 - 0x0298)
class AHospital_CeilingLight_Warm_NoShadow_C final : public AActor
{
public:
	class USpotLightComponent*                    SpotLight;                                         // 0x0298(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class URectLightComponent*                    RectLight;                                         // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   CeilingLight_New;                                  // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Hospital_CeilingLight_Warm_NoShadow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Hospital_CeilingLight_Warm_NoShadow_C")
	}
	static class AHospital_CeilingLight_Warm_NoShadow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHospital_CeilingLight_Warm_NoShadow_C>();
	}
};
DUMPER7_ASSERTS_AHospital_CeilingLight_Warm_NoShadow_C;

}

