#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IncapacitatedHuman

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass IncapacitatedHuman.IncapacitatedHuman_C
// 0x0000 (0x0368 - 0x0368)
class AIncapacitatedHuman_C final : public AIncapacitatedHuman
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("IncapacitatedHuman_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"IncapacitatedHuman_C")
	}
	static class AIncapacitatedHuman_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AIncapacitatedHuman_C>();
	}
};
DUMPER7_ASSERTS_AIncapacitatedHuman_C;

}

