#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Interact_Importer_Witness_Bargain

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Interact_Importer_Witness_Bargain.Interact_Importer_Witness_Bargain_C
// 0x0000 (0x0338 - 0x0338)
class AInteract_Importer_Witness_Bargain_C final : public ADynamicInteractableWorldItem
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Interact_Importer_Witness_Bargain_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Interact_Importer_Witness_Bargain_C")
	}
	static class AInteract_Importer_Witness_Bargain_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AInteract_Importer_Witness_Bargain_C>();
	}
};
DUMPER7_ASSERTS_AInteract_Importer_Witness_Bargain_C;

}

