#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LD_Beachfront

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LD_Beachfront.LD_Beachfront_C
// 0x0000 (0x08C0 - 0x08C0)
class ULD_Beachfront_C final : public ULevelData
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LD_Beachfront_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LD_Beachfront_C")
	}
	static class ULD_Beachfront_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULD_Beachfront_C>();
	}
};
DUMPER7_ASSERTS_ULD_Beachfront_C;

}

