#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Primary_WCQB

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Primary_WCQB.Primary_WCQB_C
// 0x0010 (0x1930 - 0x1920)
class APrimary_WCQB_C final : public AShotgun
{
public:
	class UAnimMontage*                           LightToggle1P;                                     // 0x1920(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Primary_WCQB_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Primary_WCQB_C")
	}
	static class APrimary_WCQB_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APrimary_WCQB_C>();
	}
};
DUMPER7_ASSERTS_APrimary_WCQB_C;

}

