#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RoN_Importer_Art

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RoN_Importer_Art.RoN_Importer_Art_C
// 0x0008 (0x0C98 - 0x0C90)
class ARoN_Importer_Art_C final : public AReadyOrNotLevelScript
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0C90(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_RoN_Importer_Art(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RoN_Importer_Art_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RoN_Importer_Art_C")
	}
	static class ARoN_Importer_Art_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARoN_Importer_Art_C>();
	}
};
DUMPER7_ASSERTS_ARoN_Importer_Art_C;

}

