#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RoN_Importer_Art

#include "Basic.hpp"


namespace SDK::Params
{

// Function RoN_Importer_Art.RoN_Importer_Art_C.ExecuteUbergraph_RoN_Importer_Art
// 0x0004 (0x0004 - 0x0000)
struct RoN_Importer_Art_C_ExecuteUbergraph_RoN_Importer_Art final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_RoN_Importer_Art_C_ExecuteUbergraph_RoN_Importer_Art;

}

