#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RoN_Importer_BarricadedSuspects_Core

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass RoN_Importer_BarricadedSuspects_Core.RoN_Importer_BarricadedSuspects_Core_C
// 0x0000 (0x0C90 - 0x0C90)
class ARoN_Importer_BarricadedSuspects_Core_C final : public AReadyOrNotLevelScript
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RoN_Importer_BarricadedSuspects_Core_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RoN_Importer_BarricadedSuspects_Core_C")
	}
	static class ARoN_Importer_BarricadedSuspects_Core_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ARoN_Importer_BarricadedSuspects_Core_C>();
	}
};
DUMPER7_ASSERTS_ARoN_Importer_BarricadedSuspects_Core_C;

}

