#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Scope_MicroT2

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Scope_MicroT2.Scope_MicroT2_C
// 0x0000 (0x1840 - 0x1840)
class UScope_MicroT2_C final : public UScopedWeaponAttachment
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Scope_MicroT2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Scope_MicroT2_C")
	}
	static class UScope_MicroT2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UScope_MicroT2_C>();
	}
};
DUMPER7_ASSERTS_UScope_MicroT2_C;

}

