#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sound_LookAtParameterTrigger_BP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "FMODStudio_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Sound_LookAtParameterTrigger_BP.Sound_LookAtParameterTrigger_BP_C
// 0x0050 (0x02E8 - 0x0298)
class ASound_LookAtParameterTrigger_BP_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USphereComponent*                       LookAt_Trigger;                                    // 0x02A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UBoxComponent*                          Box;                                               // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	bool                                          Persistent_Line_Check_;                            // 0x02B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2B1[0x7];                                      // 0x02B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Range_Of_Trace;                                    // 0x02B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFMODEvent*                             FMOD_Event_to_Change;                              // 0x02C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FName                                   FMOD_Parameter_to_Change;                          // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FFMODEventInstance>             FMOD_Instances;                                    // 0x02D0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          IsLookedAt;                                        // 0x02E0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void LookTriggerPersistent();
	void LookTrigger();
	void ExecuteUbergraph_Sound_LookAtParameterTrigger_BP(int32 EntryPoint);
	void BndEvt__Sound_LookAtParameterTrigger_BP_Box_K2Node_ComponentBoundEvent_1_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex);
	void BndEvt__Sound_LookAtParameterTrigger_BP_Box_K2Node_ComponentBoundEvent_0_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Sound_LookAtParameterTrigger_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Sound_LookAtParameterTrigger_BP_C")
	}
	static class ASound_LookAtParameterTrigger_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ASound_LookAtParameterTrigger_BP_C>();
	}
};
DUMPER7_ASSERTS_ASound_LookAtParameterTrigger_BP_C;

}

