#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_PresetsRoadTypeLanes

#include "Basic.hpp"

#include "E_PresetsLanesTypes_structs.hpp"


namespace SDK
{

// UserDefinedStruct ST_PresetsRoadTypeLanes.ST_PresetsRoadTypeLanes
// 0x0028 (0x0028 - 0x0000)
struct FST_PresetsRoadTypeLanes final
{
public:
	bool                                          LanesTypePresets_14_AF29FF5F44DC5AC9D5A8EB9125EE431E; // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<E_PresetsLanesTypes>                   TypeofLanes_16_14D9008B44717144FEA2AFB07D376D6A;   // 0x0008(0x0010)(Edit, BlueprintVisible)
	bool                                          TwoWaysRoad_18_DE4C02744841EE0A5E5666AE9AF6FC52;   // 0x0018(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         TwoWaysSeparatorPosition_21_6BE7073E41E4923BB08A7E81ED03B6A6; // 0x001C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ReversedWays_24_1F0AB2494DA30822B4C14DB099F8EF21;  // 0x0020(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FST_PresetsRoadTypeLanes;

}

