#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_PresetsRoadDecals

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct ST_PresetsRoadDecals.ST_PresetsRoadDecals
// 0x0008 (0x0008 - 0x0000)
struct FST_PresetsRoadDecals final
{
public:
	bool                                          Specifythenumberofprops_25_34139E664B0DA417A1776B92EDC85BFE; // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Numberofprops_26_E0E065054B862574A91B0B82AABC0BFF; // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FST_PresetsRoadDecals;

}

