#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_RoadMarking

#include "Basic.hpp"

#include "E_RoadMarkingType_structs.hpp"


namespace SDK
{

// UserDefinedStruct ST_RoadMarking.ST_RoadMarking
// 0x000C (0x000C - 0x0000)
struct FST_RoadMarking final
{
public:
	E_RoadMarkingType                             Type_7_EE32F62B4FAF780AA9E7DC96100B7FD8;           // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Offset_5_4BFE0EF844A2ACFC881563851CFF108C;         // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Yellow_6_A351BC51462431CD7ED6ABB964A40DE9;         // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FST_RoadMarking;

}

