#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ST_RoadPropsRules

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct ST_RoadPropsRules.ST_RoadPropsRules
// 0x0010 (0x0010 - 0x0000)
struct FST_RoadPropsRules final
{
public:
	class UStaticMesh*                            PropModel_20_4DF1A0E848E47B22C781BF8075B005E5;     // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          RandomRotation_24_B697ABF944AD59E9B8EF8486B2FBB217; // 0x0008(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          PositionNearEdge_27_6C309C094432D05DF63FB18A7F3EDD14; // 0x0009(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FST_RoadPropsRules;

}

