#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Customization_Selector

#include "Basic.hpp"

#include "CommonUI_classes.hpp"
#include "Engine_structs.hpp"
#include "ReadyOrNot_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_Customization_Selector.W_Customization_Selector_C
// 0x00F8 (0x03E0 - 0x02E8)
class UW_Customization_Selector_C final : public UCommonUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class Uw_Dropdown_C*                          Dropdown;                                          // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMap<class FName, class FText>                OptionsMap;                                        // 0x02F8(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          bUseGamepad;                                       // 0x0348(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_349[0x3];                                      // 0x0349(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   EquippedOptionID;                                  // 0x034C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_354[0x4];                                      // 0x0354(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Label;                                             // 0x0358(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMulticastInlineDelegate<void(class FName OptionID)> OptionSelected;                             // 0x0370(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	ECustomizationType                            Category;                                          // 0x0380(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bInitialized;                                      // 0x0381(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_382[0x6];                                      // 0x0382(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class UW_Customization_Selector_C* TriggeringSelector)> OnSelectorClicked; // 0x0388(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class FName OptionID)> OnOptionHovered;                            // 0x0398(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class Uw_Dropdown_C* TriggeringSelector)> OnDropdownClosed;        // 0x03A8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnOptionUnhovered;                                 // 0x03B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	double                                        MaxDropdownHeight;                                 // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnMenuOpened;                                      // 0x03D0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void BackPage(bool* Handled);
	void BndEvt__W_Customization_Selector_Dropdown_K2Node_ComponentBoundEvent_0_OnMenuOpened__DelegateSignature();
	void BndEvt__W_Customization_Selector_Dropdown_K2Node_ComponentBoundEvent_2_OnOptionSelected__DelegateSignature(const class FString& OptionID);
	void BndEvt__W_Customization_Selector_Dropdown_K2Node_ComponentBoundEvent_5_OnOptionHovered__DelegateSignature(const class FString& OptionID);
	void BndEvt__W_Customization_Selector_Dropdown_K2Node_ComponentBoundEvent_6_OnMenuClosed__DelegateSignature(class Uw_Dropdown_C* TriggeringDropdown);
	void BndEvt__W_Customization_Selector_Dropdown_K2Node_ComponentBoundEvent_7_OnOptionUnhovered__DelegateSignature();
	void ChangePage(class FName PageName);
	void Construct();
	void ExecuteUbergraph_W_Customization_Selector(int32 EntryPoint);
	void Hide(double Delay, bool Collapse);
	void PreConstruct(bool IsDesignTime);
	void Reveal(double Delay);
	void SetEquipped(class FName EquippedID);
	void SetInputMode(bool IsGamepad);
	void SetOptions(const TMap<class FName, class FText>& OptionsMap_0);
	void UpdateStyle(bool bUseGamepad_0);

	void GetFocusTarget(class UWidget** Focus) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_Customization_Selector_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_Customization_Selector_C")
	}
	static class UW_Customization_Selector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_Customization_Selector_C>();
	}
};
DUMPER7_ASSERTS_UW_Customization_Selector_C;

}

