#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ItemSelection_Item

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_ItemSelection_Item.W_ItemSelection_Item_C
// 0x0198 (0x0480 - 0x02E8)
class UW_ItemSelection_Item_C final : public UBaseWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anim_Focus;                                        // 0x02F0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anim_Select;                                       // 0x02F8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Anim_FadeOut;                                      // 0x0300(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBackgroundBlur*                        BG_Blur;                                           // 0x0308(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BG_Image;                                          // 0x0310(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           CanvasPanel;                                       // 0x0318(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Icon_Image;                                        // 0x0320(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Selected_Image;                                    // 0x0328(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FSlateBrush                            DefaultIcon;                                       // 0x0330(0x00D0)(Edit, BlueprintVisible, ExposeOnSpawn)
	struct FSlateColor                            BackgroundColor;                                   // 0x0400(0x0014)(Edit, BlueprintVisible, ExposeOnSpawn)
	struct FSlateColor                            IconColor;                                         // 0x0414(0x0014)(Edit, BlueprintVisible, ExposeOnSpawn)
	struct FSlateColor                            SelectedColor;                                     // 0x0428(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance)
	uint8                                         Pad_43C[0x4];                                      // 0x043C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              ED_OnAnimFadeOutFinished;                          // 0x0440(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	struct FSlateColor                            UnselectedColor;                                   // 0x0450(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          bIsPirated;                                        // 0x0464(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          InDesignTime;                                      // 0x0465(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_466[0x2];                                      // 0x0466(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              ED_OnAnimSelectFinished;                           // 0x0468(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ChangeIconsIfBuildIsPirated();
	void ConfirmSelection();
	void Construct();
	void CustomEvent_0();
	void CustomEvent_1();
	void Deselect();
	void ExecuteUbergraph_W_ItemSelection_Item(int32 EntryPoint);
	void FadeOut();
	void Initialize(const struct FSlateBrush& InBrush, bool bIsVisible);
	void OnAnimFadeOut_Finished();
	void PreConstruct(bool IsDesignTime);
	void Re_Initialize(bool bVisible);
	void Reset_Selection_Indicator();
	void Select();
	void StopConfirmAnim();
	void StopFadeOutAnim();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_ItemSelection_Item_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_ItemSelection_Item_C")
	}
	static class UW_ItemSelection_Item_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_ItemSelection_Item_C>();
	}
};
DUMPER7_ASSERTS_UW_ItemSelection_Item_C;

}

