#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_LoadoutInformationElement

#include "Basic.hpp"

#include "CommonUI_classes.hpp"
#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_LoadoutInformationElement.W_LoadoutInformationElement_C
// 0x0118 (0x0400 - 0x02E8)
class UW_LoadoutInformationElement_C final : public UCommonUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                Border;                                            // 0x02F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Name_0;                                            // 0x02F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             Type;                                              // 0x0300(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   AttachmentName;                                    // 0x0308(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   AttachmentType;                                    // 0x0320(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   EffectsName;                                       // 0x0338(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   EffectsType;                                       // 0x0350(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FLinearColor                           BorderColorAttachment;                             // 0x0368(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           BorderColorEffects;                                // 0x0378(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            TypeTextColorAttachment;                           // 0x0388(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateColor                            TypeTextColorEffects;                              // 0x039C(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateColor                            TypeTextColorEffectsPos;                           // 0x03B0(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FSlateColor                            TypeTextColorEffectsNeg;                           // 0x03C4(0x0014)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          bIsEffect;                                         // 0x03D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3D9[0x3];                                      // 0x03D9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           BorderColorEffectsPos;                             // 0x03DC(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           BorderColorEffectsNeg;                             // 0x03EC(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_W_LoadoutInformationElement(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_LoadoutInformationElement_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_LoadoutInformationElement_C")
	}
	static class UW_LoadoutInformationElement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_LoadoutInformationElement_C>();
	}
};
DUMPER7_ASSERTS_UW_LoadoutInformationElement_C;

}

