#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Options_GamepadControlScheme_UE5

#include "Basic.hpp"


namespace SDK::Params
{

// Function W_Options_GamepadControlScheme_UE5.W_Options_GamepadControlScheme_UE5_C.BndEvt__W_Options_GamepadControlScheme_UE5_Controls_OnOff_BumpersLayout_K2Node_ComponentBoundEvent_4_OnValueStateChange__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct W_Options_GamepadControlScheme_UE5_C_BndEvt__W_Options_GamepadControlScheme_UE5_Controls_OnOff_BumpersLayout_K2Node_ComponentBoundEvent_4_OnValueStateChange__DelegateSignature final
{
public:
	bool                                          bNewCheckState;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_Options_GamepadControlScheme_UE5_C_BndEvt__W_Options_GamepadControlScheme_UE5_Controls_OnOff_BumpersLayout_K2Node_ComponentBoundEvent_4_OnValueStateChange__DelegateSignature;

// Function W_Options_GamepadControlScheme_UE5.W_Options_GamepadControlScheme_UE5_C.BndEvt__W_Options_GamepadControlScheme_UE5_Controls_OnOff_HoldCrouch_K2Node_ComponentBoundEvent_0_OnValueStateChange__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct W_Options_GamepadControlScheme_UE5_C_BndEvt__W_Options_GamepadControlScheme_UE5_Controls_OnOff_HoldCrouch_K2Node_ComponentBoundEvent_0_OnValueStateChange__DelegateSignature final
{
public:
	bool                                          bNewCheckState;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_Options_GamepadControlScheme_UE5_C_BndEvt__W_Options_GamepadControlScheme_UE5_Controls_OnOff_HoldCrouch_K2Node_ComponentBoundEvent_0_OnValueStateChange__DelegateSignature;

// Function W_Options_GamepadControlScheme_UE5.W_Options_GamepadControlScheme_UE5_C.BndEvt__W_Options_GamepadOptions_UE5_Controls_OnOff_DirectionalFaceButton_K2Node_ComponentBoundEvent_2_OnValueStateChange__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct W_Options_GamepadControlScheme_UE5_C_BndEvt__W_Options_GamepadOptions_UE5_Controls_OnOff_DirectionalFaceButton_K2Node_ComponentBoundEvent_2_OnValueStateChange__DelegateSignature final
{
public:
	bool                                          bNewCheckState;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_Options_GamepadControlScheme_UE5_C_BndEvt__W_Options_GamepadOptions_UE5_Controls_OnOff_DirectionalFaceButton_K2Node_ComponentBoundEvent_2_OnValueStateChange__DelegateSignature;

// Function W_Options_GamepadControlScheme_UE5.W_Options_GamepadControlScheme_UE5_C.BndEvt__W_Options_GamepadOptions_UE5_Controls_OnOff_StickLayout_K2Node_ComponentBoundEvent_3_OnValueStateChange__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct W_Options_GamepadControlScheme_UE5_C_BndEvt__W_Options_GamepadOptions_UE5_Controls_OnOff_StickLayout_K2Node_ComponentBoundEvent_3_OnValueStateChange__DelegateSignature final
{
public:
	bool                                          bNewCheckState;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_Options_GamepadControlScheme_UE5_C_BndEvt__W_Options_GamepadOptions_UE5_Controls_OnOff_StickLayout_K2Node_ComponentBoundEvent_3_OnValueStateChange__DelegateSignature;

// Function W_Options_GamepadControlScheme_UE5.W_Options_GamepadControlScheme_UE5_C.BndEvt__W_Options_GamepadOptions_UE5_Controls_OnOff_Triggers_K2Node_ComponentBoundEvent_17_OnValueStateChange__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct W_Options_GamepadControlScheme_UE5_C_BndEvt__W_Options_GamepadOptions_UE5_Controls_OnOff_Triggers_K2Node_ComponentBoundEvent_17_OnValueStateChange__DelegateSignature final
{
public:
	bool                                          bNewCheckState;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_Options_GamepadControlScheme_UE5_C_BndEvt__W_Options_GamepadOptions_UE5_Controls_OnOff_Triggers_K2Node_ComponentBoundEvent_17_OnValueStateChange__DelegateSignature;

// Function W_Options_GamepadControlScheme_UE5.W_Options_GamepadControlScheme_UE5_C.BndEvt__W_SettingsMenuGamepad_AlternateControlsButton_K2Node_ComponentBoundEvent_62_Clicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct W_Options_GamepadControlScheme_UE5_C_BndEvt__W_SettingsMenuGamepad_AlternateControlsButton_K2Node_ComponentBoundEvent_62_Clicked__DelegateSignature final
{
public:
	class UW_Button_C*                            Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_Options_GamepadControlScheme_UE5_C_BndEvt__W_SettingsMenuGamepad_AlternateControlsButton_K2Node_ComponentBoundEvent_62_Clicked__DelegateSignature;

// Function W_Options_GamepadControlScheme_UE5.W_Options_GamepadControlScheme_UE5_C.BndEvt__W_SettingsMenuGamepad_StandardControlsButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct W_Options_GamepadControlScheme_UE5_C_BndEvt__W_SettingsMenuGamepad_StandardControlsButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature final
{
public:
	class UW_Button_C*                            Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_Options_GamepadControlScheme_UE5_C_BndEvt__W_SettingsMenuGamepad_StandardControlsButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature;

// Function W_Options_GamepadControlScheme_UE5.W_Options_GamepadControlScheme_UE5_C.ExecuteUbergraph_W_Options_GamepadControlScheme_UE5
// 0x0028 (0x0028 - 0x0000)
struct W_Options_GamepadControlScheme_UE5_C_ExecuteUbergraph_W_Options_GamepadControlScheme_UE5 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_Button_C*                            K2Node_ComponentBoundEvent_Button_1;               // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bNewCheckState_4;       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetGamepadInvertStickLayout_ReturnValue;  // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bNewCheckState_3;       // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetGamepadInvertTriggersLayout_ReturnValue; // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bNewCheckState_2;       // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetGamepadInvertButtonLayout_ReturnValue; // 0x0016(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bNewCheckState_1;       // 0x0017(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SaveHoldCrouch_ReturnValue;               // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_ComponentBoundEvent_bNewCheckState;         // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SetGamepadSwitchBumpersTriggersLayout_ReturnValue; // 0x001A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x001B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SavePS5AdaptiveAimTriggers_ReturnValue;   // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SavePS5AdaptiveFireTriggers_ReturnValue;  // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1E[0x2];                                       // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UW_Button_C*                            K2Node_ComponentBoundEvent_Button;                 // 0x0020(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_Options_GamepadControlScheme_UE5_C_ExecuteUbergraph_W_Options_GamepadControlScheme_UE5;

// Function W_Options_GamepadControlScheme_UE5.W_Options_GamepadControlScheme_UE5_C.Populate Settings
// 0x000A (0x000A - 0x0000)
struct W_Options_GamepadControlScheme_UE5_C_Populate_Settings final
{
public:
	bool                                          CallFunc_GetGamepadSwitchBumpersTriggersLayout_bSwitchBumpersTriggers; // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetGamepadSwitchBumpersTriggersLayout_ReturnValue; // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LoadHoldCrouch_HoldCrouch;                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LoadHoldCrouch_ReturnValue;               // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetGamepadInvertStickLayout_bInvertStickLayout; // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetGamepadInvertStickLayout_ReturnValue;  // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetGamepadInvertButtonLayout_bInvertButtonLayout; // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetGamepadInvertButtonLayout_ReturnValue; // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetGamepadInvertTriggersLayout_bInvertTriggersLayout; // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetGamepadInvertTriggersLayout_ReturnValue; // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_Options_GamepadControlScheme_UE5_C_Populate_Settings;

// Function W_Options_GamepadControlScheme_UE5.W_Options_GamepadControlScheme_UE5_C.Reset to Default
// 0x0008 (0x0008 - 0x0000)
struct W_Options_GamepadControlScheme_UE5_C_Reset_to_Default final
{
public:
	class UReadyOrNotGameUserSettings*            CallFunc_GetReadyOrNotGameUserSettings_ReturnValue; // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_Options_GamepadControlScheme_UE5_C_Reset_to_Default;

// Function W_Options_GamepadControlScheme_UE5.W_Options_GamepadControlScheme_UE5_C.BP_GetDesiredFocusTarget
// 0x0008 (0x0008 - 0x0000)
struct W_Options_GamepadControlScheme_UE5_C_BP_GetDesiredFocusTarget final
{
public:
	class UWidget*                                ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_W_Options_GamepadControlScheme_UE5_C_BP_GetDesiredFocusTarget;

}

