#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_SwatCommandEntry

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_SwatCommandEntry.W_SwatCommandEntry_C
// 0x0010 (0x03B0 - 0x03A0)
class UW_SwatCommandEntry_C final : public USwatCommandEntryWidget
{
public:
	class UW_GamepadButtonImage_C*                NavigateBackImage;                                 // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UW_GamepadButtonImage_C*                NavigateConfirmImage;                              // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("W_SwatCommandEntry_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"W_SwatCommandEntry_C")
	}
	static class UW_SwatCommandEntry_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UW_SwatCommandEntry_C>();
	}
};
DUMPER7_ASSERTS_UW_SwatCommandEntry_C;

}

