#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBA_Search

#include "Basic.hpp"

#include "ReadyOrNot_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WBA_Search.WBA_Search_C
// 0x0000 (0x02A0 - 0x02A0)
class UWBA_Search_C final : public UWorldBuildingActivity
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBA_Search_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBA_Search_C")
	}
	static class UWBA_Search_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBA_Search_C>();
	}
};
DUMPER7_ASSERTS_UWBA_Search_C;

}

